[circleci][config] Use 'bot/check-changed-files-or-halt' + bump 'cimg/ruby' to v4
Finally, after making some tests, using the command
`git show HEAD^..HEAD [...]` wasn't working as expected

So we can try to use the `bot/check-changed-files-or-halt` job (define
on CircleCI Orb), and this time check if there is a change on specific
files between `master` and `HEAD` branch

We also bump the `cimg/ruby` from v3.0 to v4.0, because we were facing
to some strange error:
```
ERROR: failed to build: Error response from daemon: client version 1.52 is too new. Maximum supported API version is 1.43: driver not connecting
make: *** [Makefile:18: build] Error 1
```